### ISSUE TITLE
🧐[求助] 今天构建的时候忽然提示如下错误， 我尝试很多方法都无法解决， 求助啊！

### ISSUE THREAD

**Issue by egene-huang** [ant-design/pro-components#1592]
### 🧐 问题描述
这是构建中的错误信息:
`
[91mError: Couldn't find any versions for "@typescript-eslint/scope-manager" that matches "4.13.0"
at MessageError.ExtendableBuiltin (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:721:66)
at new MessageError (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:750:123)
at Function. (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:50546:13)
at Generator.next ()
at step (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:310:30)
at /usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:321:13
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0m[91mError: Couldn't find any versions for "@typescript-eslint/types" that matches "4.13.0"
at MessageError.ExtendableBuiltin (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:721:66)
at new MessageError (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:750:123)
at Function. (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:50546:13)
at Generator.next ()
at step (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:310:30)
at /usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:321:13
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0m[91mError: Couldn't find any versions for "@typescript-eslint/types" that matches "4.13.0"
at MessageError.ExtendableBuiltin (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:721:66)
at new MessageError (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:750:123)
at Function. (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:50546:13)
at Generator.next ()
at step (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:310:30)
at /usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:321:13
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find any versions for "@typescript-eslint/visitor-keys" that matches "4.13.0"
at MessageError.ExtendableBuiltin (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:721:66)
at new MessageError (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:750:123)
at Function. (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:50546:13)
at Generator.next ()
at step (/usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:310:30)
at /usr/local/node-v12.18.3-linux-x64/lib/node_modules/yarn/lib/cli.js:321:13
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0mRemoving intermediate container e4b7d371cba9
The command '/bin/sh -c yarn install' returned a non-zero code: 1
`
一下三个依赖找不到:

> @typescript-eslint/types@4.13.0
@typescript-eslint/scope-manager@4.13.0
@typescript-eslint/visitor-keys@4.13.0

x使用yarn分析了是`@umijs/fabric` 依赖了 `@typescript-eslint/eslint-plugin` 然后 才依赖了上面三个，我首先将`@umijs/fabric`升级到最新@2.4.11 然后手动安装了 `yarn add @typescript-eslint/eslint-plugin --dev`  可是问题依然没有解决， 请问这是为什么呀？  求助， 我实在搞不定这个问题了  谢谢你们了!!!

**Comment by egene-huang** [comment]
解决了, 关闭
