### ISSUE TITLE
使用less构建样式@ant-design/pro-card文件报错

### ISSUE THREAD

**Issue by sharh** [ant-design/pro-components#2155]
lessContent文件内容：
```less
@import '~antd/dist/antd.less';
@import '@ant-design/**/*.less';
@import './overrides.common.less';
```

```js
const less = require('less');
var LessPluginAutoPrefix = require('less-plugin-autoprefix');
let autoprefixPlugin = new LessPluginAutoPrefix({ browsers: ['last 2 versions'] });
var NpmImportPlugin = require('less-plugin-npm-import');
var LessPluginGlob = require('less-plugin-glob');
// 编译js
let renderContent = await less.render(lessContent, {
  paths: ['node_modules', 'src/themes/'],
  javascriptEnabled: true,
  math: 'always',
  plugins: [autoprefixPlugin, new NpmImportPlugin({ prefix: '~' }), LessPluginGlob],
});

```

window10系统

错误信息如下：
```
RangeError: Maximum call stack size exceeded
    at Ruleset.eval (F:\1projects\terminal-pc\node_modules\less\lib\less\tree\ruleset.js:151:32)
    at Definition.evalCall (F:\1projects\terminal-pc\node_modules\less\lib\less\tree\mixin-definition.js:161:27)
    at MixinCall.eval (F:\1projects\terminal-pc\node_modules\less\lib\less\tree\mixin-call.js:143:50)
    at Ruleset.eval (F:\1projects\terminal-pc\node_modules\less\lib\less\tree\ruleset.js:142:30)
    at Definition.evalCall (F:\1projects\terminal-pc\node_modules\less\lib\less\tree\mixin-definition.js:161:27)
    at MixinCall.eval (F:\1projects\terminal-pc\node_modules\less\lib\less\tree\mixin-call.js:143:50)
    at Ruleset.eval (F:\1projects\terminal-pc\node_modules\less\lib\less\tree\ruleset.js:142:30)
    at Definition.evalCall (F:\1projects\terminal-pc\node_modules\less\lib\less\tree\mixin-definition.js:161:27)
    at MixinCall.eval (F:\1projects\terminal-pc\node_modules\less\lib\less\tree\mixin-call.js:143:50)
    at Ruleset.eval (F:\1projects\terminal-pc\node_modules\less\lib\less\tree\ruleset.js:142:30) {
  message: 'Maximum call stack size exceeded',
  stack: 'RangeError: Maximum call stack size exceeded\n' +
    '    at Ruleset.eval (F:\\1projects\\terminal-pc\\node_modules\\less\\lib\\less\\tree\\ruleset.js:151:32)\n' +
    '    at Definition.evalCall (F:\\1projects\\terminal-pc\\node_modules\\less\\lib\\less\\tree\\mixin-definition.js:161:27)\n' +
    '    at MixinCall.eval (F:\\1projects\\terminal-pc\\node_modules\\less\\lib\\less\\tree\\mixin-call.js:143:50)\n' +
    '    at Ruleset.eval (F:\\1projects\\terminal-pc\\node_modules\\less\\lib\\less\\tree\\ruleset.js:142:30)\n' +
    '    at Definition.evalCall (F:\\1projects\\terminal-pc\\node_modules\\less\\lib\\less\\tree\\mixin-definition.js:161:27)\n' +
    '    at MixinCall.eval (F:\\1projects\\terminal-pc\\node_modules\\less\\lib\\less\\tree\\mixin-call.js:143:50)\n' +
    '    at Ruleset.eval (F:\\1projects\\terminal-pc\\node_modules\\less\\lib\\less\\tree\\ruleset.js:142:30)\n' +
    '    at Definition.evalCall (F:\\1projects\\terminal-pc\\node_modules\\less\\lib\\less\\tree\\mixin-definition.js:161:27)\n' +
    '    at MixinCall.eval (F:\\1projects\\terminal-pc\\node_modules\\less\\lib\\less\\tree\\mixin-call.js:143:50)\n' +
    '    at Ruleset.eval (F:\\1projects\\terminal-pc\\node_modules\\less\\lib\\less\\tree\\ruleset.js:142:30)',
  type: 'Syntax',
  filename: 'F:/1projects/terminal-pc/node_modules/@ant-design/pro-card/lib/style/index.less',
  index: 3139,
  line: 169,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '.loop-grid-columns(@grid-columns);', '' ]
}
```

**Comment by chenshuai2144** [comment]
@import '@ant-design/**/*.less';

真的有这个语法吗，感觉性能会不可接受

**Comment by sharh** [comment]
> @import '@ant-design/**/*.less';
> 
> 真的有这个语法吗，感觉性能会不可接受

这个插件`less-plugin-glob`支持使用这种语法的

**Comment by chenshuai2144** [comment]
循环依赖了吗? 这个我也不熟，能帮忙 debug 一下吗

**Comment by qiuziGirl** [comment]
> > @import '@ant-design/**/*.less';
> > 真的有这个语法吗，感觉性能会不可接受
> 
> 这个插件`less-plugin-glob`支持使用这种语法的。性能没有发现什么问题，安装pro-card后就会出现上面的报错，应该是 pro-card下的less样式文件这个写法有点问题：
> 
> > @ant-design/pro-card/lib/style/index.less
> 
> ```css-less
> .loop-grid-columns(@grid-columns);
> ```



> > @import '@ant-design/**/*.less';
> > 真的有这个语法吗，感觉性能会不可接受
> 
> 这个插件`less-plugin-glob`支持使用这种语法的。性能没有发现什么问题，安装pro-card后就会出现上面的报错，应该是 pro-card下的less样式文件这个写法有点问题：
> 
> > @ant-design/pro-card/lib/style/index.less
> 
> ```css-less
> .loop-grid-columns(@grid-columns);
> ```

你好，遇到同样问题，请问最后怎么解决？
