### ISSUE TITLE
🐛[BUG] 在electron中使用pro-layout,点击菜单会报栈溢出异常

### ISSUE THREAD

**Issue by fullee** [ant-design/pro-components#2845]
### 🐛 bug 描述
> 异常信息：
```js
index.js:9 Uncaught RangeError: Maximum call stack size exceeded
    at equal (index.js:9)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
equal @ index.js:9
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
equal @ index.js:64
Show 170 more frames
react-dom.development.js:20085 The above error occurred in the <BasicLayout> component:

    at BasicLayout (http://localhost:3000/main_window/index.js:43714:73)
    at Home (http://localhost:3000/main_window/index.js:187452:22)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
react-dom.development.js:11340 Uncaught RangeError: Maximum call stack size exceeded
    at equal (index.js:9)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
    at equal (index.js:64)
```

### 📷 复现步骤

反复点击两个菜单

### 💻 复现代码

ProLayout的menuItemRender和route，两个菜单往复点击时会出现上面的异常：            
```jsx
  route={{
      path: '/',
      routes: [
          {
              path: '/detect',
              icon: <ExperimentOutlined/>,
              name: '检测'
          },
          {
              path: '/records',
              icon: <ProfileOutlined/>,
              name: '检测记录'
          }
      ]
  }}
  menuItemRender={(item, dom) => (
      <a onClick={() => {
          setPathname(item.path || '/welcome');
      }}>{dom}</a>
  )}
```
### © 版本信息

- ProComponents 版本: [ "@ant-design/pro-layout": "^6.19.0"]
- umi 版本 无
- 浏览器环境 "electron": "12.0.6"
- 开发环境 [mac OS，windows10都有这样的问题]

### 🚑 其他信息

复现仓库：
https://github.com/fullee/ele/tree/issue2845
issue2845分支复现了这个bug，如图反复点击这两个菜单项：
![image](https://user-images.githubusercontent.com/11188837/119500493-72965480-bd9a-11eb-9f1b-3332e680a35a.png)

**Comment by chenshuai2144** [comment]
手动console 一下把，感觉时你的 effect 写的有问题。光 setState 不会报错的

**Comment by fullee** [comment]
@chenshuai2144 有个例子吗，没太看明白您的意思

**Comment by chenshuai2144** [comment]
https://github.com/fullee/ele/blob/6f5d8ee8a4674ddd83e257c5afa6c28fb0000bfc/src/app.tsx#L60


console 一下这里把，我觉得是这里的原因

**Comment by fullee** [comment]
渲染线程调用的是下面的文件
https://github.com/fullee/ele/blob/6f5d8ee8a4674ddd83e257c5afa6c28fb0000bfc/src/home.tsx#L42

**Comment by chenshuai2144** [comment]
menuItemRender 是多次调用的结果，不是多次调用的原因

**Comment by liihuu** [comment]
问题解决了吗，我在普通的web程序上遇到同样的问题，但是我是打包成生产才会有这样。

**Comment by fullee** [comment]
@liihuu 细节忘记了
