### ISSUE TITLE
🐛[BUG] 安装依赖找不到，查了似乎有tag，但是没有包？

### ISSUE THREAD

**Issue by mctl** [ant-design/pro-components#4176]
### 🐛 bug 描述

安装依赖报错

Error: Couldn't find any versions for "@ant-design/pro-form" that matches "1.49.6"
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.13.0/lib/cli.js:727:66)
    at new MessageError (/opt/yarn-v1.13.0/lib/cli.js:756:123)
    at Function.<anonymous> (/opt/yarn-v1.13.0/lib/cli.js:49808:13)
    at Generator.next (<anonymous>)
    at step (/opt/yarn-v1.13.0/lib/cli.js:304:30)
    at /opt/yarn-v1.13.0/lib/cli.js:315:13
    at process._tickCallback (internal/process/next_tick.js:68:7)

### 📷 复现步骤

本地项目重装依赖

### 🏞 期望结果

正常安装

### 💻 复现代码

无

**Comment by mctl** [comment]
私有仓库问题
