### ISSUE TITLE
🐛[BUG]依赖antd版本问题

### ISSUE THREAD

**Issue by 201753010** [ant-design/pro-components#5724]
场景：
我的项目package依赖antd版本锁死4.10.2了，使用@ant-design/pro-form出现报错现象，导致我的页面不能显示。

检查后：
@ant-design/pro-form里的package.json的antd的版本没有锁死，导致@ant-design/pro-form使用antd依赖时引用了我项目里的antd@4.10.2版本后出现bug，所以希望能解决这个问题，谢谢

```
TypeError: Cannot read properties of undefined (reading '_context')
    at useContext (react.development.js:1481:1)
    at BaseFormComponents (BaseForm.js:82:1)
    at renderWithHooks (react-dom.development.js:14803:1)
    at mountIndeterminateComponent (react-dom.development.js:17482:1)
    at beginWork (react-dom.development.js:18596:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at beginWork$1 (react-dom.development.js:23203:1)
    at performUnitOfWork (react-dom.development.js:22157:1)
    at workLoopSync (react-dom.development.js:22130:1)
    at performSyncWorkOnRoot (react-dom.development.js:21756:1)
    at react-dom.development.js:11089:1
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084:1)
    at flushSyncCallbackQueue (react-dom.development.js:11072:1)
    at discreteUpdates$1 (react-dom.development.js:21893:1)
    at discreteUpdates (react-dom.development.js:806:1)
    at dispatchDiscreteEvent (react-dom.development.js:4168:1) {componentStack: '\n    in BaseFormComponents (created by BaseForm)\n …le.tsx:57)\n    in _LocaleContainer\n    in Unknown'}
```

**Comment by chenshuai2144** [comment]
那你也要锁 pro-from 了，我们用了不少高级API
有些API 就是在antd里面加的

**Comment by birdycn** [comment]
> 那你也要锁 pro-from 了，我们用了不少高级API 有些API 就是在antd里面加的

应该怎么解决呢
