### ISSUE TITLE
🐛[BUG] @ant-design/pro-layout 从 6.15.3 升级到 7.0.2 报 找不到 PageLoading

### ISSUE THREAD

**Issue by hyzx86** [ant-design/pro-components#5857]
### 🐛 bug 描述

最近发现动态设置 Layout 的 Token 需要升级到新版本，我用的 5.15.3

结果运行时候直接报错了。。 `filePath not found of @ant-design/pro-layout/es/PageLoading`

```  LOG
AssertionError [ERR_ASSERTION]: filePath not found of @ant-design/pro-layout/es/PageLoading
    at D:\myProject\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:119:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\myProject\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:64:103)
    at _next (D:\myProject\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:194)
    at D:\myProject\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:364
    at new Promise (<anonymous>)
    at D:\myProject\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:97
    at figureOutExport (D:\myProject\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:129:17)
    at D:\myProject\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:184:201
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\myProject\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:84:103)
    at _next (D:\myProject\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:86:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### 📷 复现步骤

yarn @ant-design/pro-layout 升级到了最新版 7.0.2 

### © 版本信息

依赖信息如下：
```
  "dependencies": {
    "@ant-design/flowchart": "^1.1.3",
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^1.1.5",
    "@ant-design/pro-descriptions": "^1.6.8",
    "@ant-design/pro-form": "^1.18.3",
    "@ant-design/pro-layout": "^7.0.2",
    "@ant-design/pro-table": "^2.30.8",
    "@antv/data-set": "^0.11.0",
    "@antv/l7": "^2.3.7",
    "@antv/l7-maps": "^2.3.7",
    "@antv/l7-react": "^2.1.9",
    "@fortawesome/fontawesome-free": "^6.1.1",
    "@umijs/route-utils": "^2.0.0",
    "ahooks": "^2.0.0",
    "amis": "2.2.0",
    "amis-core": "2.2.0",
    "amis-editor": "5.1.9",
    "amis-ui": "2.2.0",
    "amis-widget": "^1.3.8",
    "antd": "^4.20.0",
    "axios": "^0.27.2",
    "bizcharts": "^3.5.3-beta.0",
    "bizcharts-plugin-slider": "^2.1.1-beta.1",
    "classnames": "^2.3.0",
    "copy-to-clipboard": "^3.3.1",
    "gg-editor": "^2.0.2",
    "lodash": "^4.17.0",
    "lodash-decorators": "^6.0.0",
    "moment": "^2.29.0",
    "numeral": "^2.0.6",
    "nzh": "^1.0.3",
    "oidc-client": "^1.11.5",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-fittext": "^1.0.0",
    "react-full-screen": "^1.1.1",
    "react-helmet-async": "^1.2.0",
    "react-router": "^4.3.1",
    "umi": "^3.5.0",
    "umi-serve": "^1.9.10"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.0",
    "@playwright/test": "^1.17.0",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.0",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "17.0.14",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.11.1",
    "@umijs/openapi": "^1.3.0",
    "@umijs/plugin-blocks": "^2.2.0",
    "@umijs/plugin-esbuild": "^1.4.0",
    "@umijs/plugin-openapi": "^1.3.0",
    "@umijs/preset-ant-design-pro": "^1.3.0",
    "@umijs/preset-dumi": "^1.1.0",
    "@umijs/preset-react": "^2.1.0",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.3.0",
    "detect-installer": "^1.0.0",
    "enzyme": "^3.11.0",
    "eslint": "^7.32.0",
    "express": "^4.17.1",
    "gh-pages": "^3.2.0",
    "jsdom-global": "^3.0.0",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.1.0",
    "monaco-editor-webpack-plugin": "6.0.0",
    "prettier": "^2.5.0",
    "puppeteer-core": "^8.0.0",
    "stylelint": "^13.0.0",
    "swagger-ui-react": "^4.11.0",
    "typescript": "^4.5.0",
    "umi-serve": "^1.9.10"
  },
```

**Comment by hyzx86** [comment]
已解决

@ant-design/pro-layout/es/PageLoading  没有了， 要改成
 @ant-design/pro-layout/es/components/PageLoading
后面还有个 local 和 defaultSettings 
lib 文件夹木有了，需要改成 es

**Comment by yangbinsoft** [comment]
我怎么还是不行呢
![image](https://user-images.githubusercontent.com/15042338/192462533-7b963457-edde-4646-aef0-d5b8f1f6345a.png)

**Comment by hyzx86** [comment]
> 我怎么还是不行呢 ![image](https://user-images.githubusercontent.com/15042338/192462533-7b963457-edde-4646-aef0-d5b8f1f6345a.png)

别升了，5.2.0 凑合用得了。。这个问题解决了还有其它问题，烦的一批。。还是抽空迁移代码到新框架好了
不要浪费时间了

**Comment by hyzx86** [comment]
需要 Umi 4  Antd 6.x 改的不少，简单点还是迁移逻辑代码比较靠谱

**Comment by Kakaeex** [comment]
> 已解决
> 
> @ant-design/pro-layout/es/PageLoading 没有了， 要改成 @ant-design/pro-layout/es/components/PageLoading 后面还有个 local 和 defaultSettings lib 文件夹木有了，需要改成 es

按这个就不报错了！thx！~
