### ISSUE TITLE
🐛[BUG] Cannot read properties of undefined (reading 'colorTextBase')

### ISSUE THREAD

**Issue by fitterfizzle** [ant-design/pro-components#6109]
Since v3.0.19 following error appears everywhere:

```
TypeError: Cannot read properties of undefined (reading 'colorTextBase')
    at getLayoutDesignToken (layoutToken.js:11:1)
    at index.js:208:1
    at mountMemo (react-dom.development.js:15846:1)
    at Object.useMemo (react-dom.development.js:16219:1)
    at useMemo (react.development.js:1532:1)
    at ConfigProviderWrap (index.js:199:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at batchedUpdates$1 (react-dom.development.js:22387:1)
    at notifyManager.ts:61:1 
```

**Comment by fitterfizzle** [comment]
v3.0.20 seems to have solved the issue! Many thanks.

**Comment by niunai2016** [comment]
升级最新的antd可解决
