### ISSUE TITLE
🐛[BUG] pro-components 在 nextjs 中无法使用。

### ISSUE THREAD

**Issue by lifegit** [ant-design/pro-components#6321]
### 🐛 bug 描述

pro-components 在 nextjs 中无法使用。

### 📷 复现步骤

1. `npx create-next-app --example with-ant-design with-ant-design-app`
2. `npm i @ant-design/pro-components  --save`
3. write index.tsx
4. run command: `next`
5. throw err :
`
➜  with-ant-design git:(main) ✗ next                                    
warn  - Port 3000 is in use, trying 3001 instead.
ready - started server on 0.0.0.0:3001, url: http://localhost:3001
event - compiled client and server successfully in 844 ms (160 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 2.4s (3322 modules)
error - /Users/yxs/with-ant-design/node_modules/@ant-design/pro-components/es/index.js:1
export * from '@ant-design/pro-card';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.@ant-design/pro-components (/Users/yxs/with-ant-design/.next/server/pages/index.js:32:18)
    at __webpack_require__ (/Users/yxs/with-ant-design/.next/server/webpack-runtime.js:33:42) {
  page: '/'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 253 ms (3323 modules)

`

### 🚑 其他信息

[复现仓库 with-ant-design ](https://github.com/lifegit/with-ant-design)

**Comment by chenshuai2144** [comment]
pro-components 是在浏览器中运行的包，你要在 node中运行要配置 编译的，你要自己处理一下类似 jest 处理 import

**Comment by dzcpy** [comment]
楼主解决了吗？

**Comment by chenshuai2144** [comment]
需要升级最新版本
