### ISSUE TITLE
[Bug] Next Js will not use the PageHeader

### ISSUE THREAD

**Issue by dickwu** [ant-design/pro-components#6328]
### Reproduction link

[https://github.com/dickwu/antd5-bug-test](https://github.com/dickwu/antd5-bug-test)

### Steps to reproduce

Just run: yarn dev & open http://localhost:3000

### What is expected?

Normal page

### What is actually happening?

Error:
import 'antd/es/anchor/style';
^^^^^^

SyntaxError: Cannot use import statement outside a module

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 18.0.26 |
| System | macOS 13.1 (arm64) |
| Browser | Chrome 108 |

**Comment by dickwu** [comment]
更新到最新版后出现如下问题
```
import _defineProperty from "@babel/runtime/helpers/esm/defineProperty";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/lifefarmer/opensource/antd5-test/node_modules/@ant-design/pro-layout/lib/index.js:103:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
```

**Comment by luisbobadilla** [comment]
i have the same problem
any idea?

**Comment by chenshuai2144** [comment]
If you can I recommend upgrading to the latest version, we provide the corresponding lib version

**Comment by thonatos** [comment]
@chenshuai2144 the latest version still can't work ~

```js
dev: import _defineProperty from "@babel/runtime/helpers/esm/defineProperty";
dev: ^^^^^^
dev: 
dev: SyntaxError: Cannot use import statement outside a module
```

**Comment by chenshuai2144** [comment]
you can use import xxx form '@ant-design/pro-layout/lib'

**Comment by jelatomgt** [comment]
@chenshuai2144 
still not working.
i faced same problem. i use what you say.(@ant-design/pro-layout/lib)
but it does not work in nextjs.

we cannot use PageHeader in pro-layout...

**Comment by tonywei92** [comment]
@chenshuai2144 mine also not working
```
import { Keyframes } from '@ant-design/cssinjs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/tonysong/Projects/planetsurf/rapid-erp-fe/node_modules/@ant-design/pro-skeleton/lib/index.js:61:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/tonysong/Projects/planetsurf/rapid-erp-fe/node_modules/@ant-design/pro-descriptions/lib/index.js:18:43)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/tonysong/Projects/planetsurf/rapid-erp-fe/node_modules/@ant-design/pro-components/lib/index.js:17:24)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at @ant-design/pro-components/lib (/home/tonysong/Projects/planetsurf/rapid-erp-fe/.next/server/pages/index.js:52:18)
    at __webpack_require__ (/home/tonysong/Projects/planetsurf/rapid-erp-fe/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/components/layouts/Master/index.tsx:15:88)
    at ./src/components/layouts/Master/index.tsx (/home/tonysong/Projects/planetsurf/rapid-erp-fe/.next/server/pages/index.js:22:1)
    at __webpack_require__ (/home/tonysong/Projects/planetsurf/rapid-erp-fe/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/index.tsx:9:84)
    at ./src/pages/index.tsx (/home/tonysong/Projects/planetsurf/rapid-erp-fe/.next/server/pages/index.js:32:1)
    at __webpack_require__ (/home/tonysong/Projects/planetsurf/rapid-erp-fe/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/home/tonysong/Projects/planetsurf/rapid-erp-fe/.next/server/pages/index.js:112:39)
    at /home/tonysong/Projects/planetsurf/rapid-erp-fe/.next/server/pages/index.js:113:28
    at Object.<anonymous> (/home/tonysong/Projects/planetsurf/rapid-erp-fe/.next/server/pages/index.js:116:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (/home/tonysong/Projects/planetsurf/rapid-erp-fe/node_modules/next/dist/server/require.js:88:12)
    at /home/tonysong/Projects/planetsurf/rapid-erp-fe/node_modules/next/dist/server/load-components.js:37:73
    at async Object.loadComponents (/home/tonysong/Projects/planetsurf/rapid-erp-fe/node_modules/next/dist/server/load-components.js:37:26)
    at async DevServer.findPageComponents (/home/tonysong/Projects/planetsurf/rapid-erp-fe/node_modules/next/dist/server/next-server.js:562:36) {
  page: '/'````

**Comment by rimshashakoor0809** [comment]
Did anyone find the solution for the above-mentioned problem? I'm getting a similar error when importing PageHeader from '@ant-design/pro-layout'. The error is: Module not found: Can't resolve 'antd/lib/version/style'.

https://nextjs.org/docs/messages/module-not-found

Import trace for the requested module:

../../node_modules/@ant-design/pro-layout/es/index.js
../../libs/shared-components/src/PageHeader/elements.tsx
../../libs/shared-components/src/PageHeader/PageHeader.tsx
../../libs/shared-components/src/PageHeader/index.tsx
../../libs/shared-components/src/index.ts
./pages/dashboard/index.tsx
