### ISSUE TITLE
🐛[BUG] "Warning: useLayoutEffect does nothing on the server"

### ISSUE THREAD

**Issue by neongreen** [ant-design/pro-components#6417]
I use pro-components in a Next.js app. When running in dev mode, I get a lot of warnings about `useLayoutEffect`:

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

    at Provider (/Users/artyom/neongreen/webdev/.yarn/cache/unstated-next-npm-1.1.0-88f5c1706b-8e1c75ea3f.zip/node_modules/unstated-next/dist/unstated-next.js:11:31)
    at ProviderTableContainer (/Users/artyom/neongreen/webdev/.yarn/__virtual__/@ant-design-pro-table-virtual-35e1441880/0/cache/@ant-design-pro-table-patch-5349278b13-8fcc52f9d1.zip/node_modules/@ant-design/pro-table/lib/Table.js:711:43)
    at ProList (/Users/artyom/neongreen/webdev/.yarn/__virtual__/@ant-design-pro-list-virtual-ba8571e482/0/cache/@ant-design-pro-list-patch-1d9058bbb9-9d0d6fda7f.zip/node_modules/@ant-design/pro-list/lib/index.js:23:22)
    at ...
```

Versions:

```json
    "@ant-design/cssinjs": "^1.2.0",
    "@ant-design/icons": "^4.8.0",
    "@ant-design/pro-list": "^2.0.40",
    "@ant-design/pro-provider": "^2.2.0",
    "antd": "^5.1.0",
    "react": "18.2.0",
    "next": "^13.1.0",
```

It doesn't seem like it leads to any issues, but maybe I'm wrong. And it would be nice to not have the warning.

**Comment by chenshuai2144** [comment]
忽略一下吧，这个没啥影响，ssr 比较容易碰到这个问题，一般是通过useLayoutEffect 替换为 useEffect 来绕过的
