### ISSUE TITLE
pnpm run openapi报错🧐[问题]

### ISSUE THREAD

**Issue by webguicai** [ant-design/pro-components#7058]
### 🧐 问题描述

[openAPI]: 💺 将 Swagger 转化为 openAPI
/Users/jiangyichen/Desktop/work/Industrial-Internet/node_modules/.pnpm/swagger2openapi@7.0.8/node_modules/swagger2openapi/index.js:1347
            else return reject(new S2OError('(Patchable) info.termsOfService must be a URL'));
                               ^

S2OError: (Patchable) info.termsOfService must be a URL
    at fixInfo (/Users/jiangyichen/Desktop/work/Industrial-Internet/node_modules/.pnpm/swagger2openapi@7.0.8/node_modules/swagger2openapi/index.js:1347:32)
    at /Users/jiangyichen/Desktop/work/Industrial-Internet/node_modules/.pnpm/swagger2openapi@7.0.8/node_modules/swagger2openapi/index.js:1522:9
    at new Promise (<anonymous>)
    at Object.convertObj (/Users/jiangyichen/Desktop/work/Industrial-Internet/node_modules/.pnpm/swagger2openapi@7.0.8/node_modules/swagger2openapi/index.js:1384:28)
    at /Users/jiangyichen/Desktop/work/Industrial-Internet/node_modules/.pnpm/@umijs+openapi@1.8.2/node_modules/@umijs/openapi/dist/index.js:28:35
    at new Promise (<anonymous>)
    at converterSwaggerToOpenApi (/Users/jiangyichen/Desktop/work/Industrial-Internet/node_modules/.pnpm/@umijs+openapi@1.8.2/node_modules/@umijs/openapi/dist/index.js:27:12)
    at /Users/jiangyichen/Desktop/work/Industrial-Internet/node_modules/.pnpm/@umijs+openapi@1.8.2/node_modules/@umijs/openapi/dist/index.js:63:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiangyichen/Desktop/work/Industrial-Internet/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:164:62)
 ELIFECYCLE  Command failed with exit code 1.

### 💻 示例代码

  openAPI: [
    {
      requestLibPath: "import { request } from '@umijs/max'",
      // 或者使用在线的版本
      // schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json"
      schemaPath: join(__dirname, 'oneapi.json'),
      mock: false,
    },
    {
      requestLibPath: "import { request } from '@umijs/max'",
      // schemaPath: 'http://20.20.129.218:8002/internet-web/v2/api-docs?group=group_name',
      schemaPath: join(__dirname, 'openapi.json'),
      projectName: 'industrial-internet',
      mock: false
    },
  ],

openapi.js下的内容
![image](https://github.com/ant-design/pro-components/assets/77370829/41d4f168-f7b8-41e5-a304-3833fa311e69)

**Comment by chenshuai2144** [comment]
这个库是社区自维护的，你去那边看看吧
