### ISSUE TITLE
🐛[BUG] ProTable 在 React.StrictMode 模式下 findDOMNode 警告问题

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/pro-components#7885]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProTable 在 React.StrictMode 模式下 findDOMNode 警告问题
警告信息如下：
```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at span
    at eval (https://g7sg44.csb.app/node_modules/@ant-design/icons/es/components/AntdIcon.js:29:25)
    at ColumnHeightOutlined
    at eval (https://g7sg44.csb.app/node_modules/@rc-component/trigger/es/TriggerWrapper.js:9:24)
    at DomWrapper (https://g7sg44.csb.app/node_modules/rc-resize-observer/es/SingleObserver/DomWrapper.js:27:33)
    at SingleObserver (https://g7sg44.csb.app/node_modules/rc-resize-observer/es/SingleObserver/index.js:17:24)
    at ResizeObserver (https://g7sg44.csb.app/node_modules/rc-resize-observer/es/index.js:26:24)
    at eval (https://g7sg44.csb.app/node_modules/@rc-component/trigger/es/index.js:51:34)
    at Tooltip (https://g7sg44.csb.app/node_modules/rc-tooltip/es/Tooltip.js:21:32)
    at eval (https://g7sg44.csb.app/node_modules/antd/es/tooltip/index.js:37:21)
    at eval (https://g7sg44.csb.app/node_modules/@rc-component/trigger/es/TriggerWrapper.js:9:24)
    at DomWrapper (https://g7sg44.csb.app/node_modules/rc-resize-observer/es/SingleObserver/DomWrapper.js:27:33)
    at SingleObserver (https://g7sg44.csb.app/node_modules/rc-resize-observer/es/SingleObserver/index.js:17:24)
    at ResizeObserver (https://g7sg44.csb.app/node_modules/rc-resize-observer/es/index.js:26:24)
    at eval (https://g7sg44.csb.app/node_modules/@rc-component/trigger/es/index.js:51:34)
    at Dropdown (https://g7sg44.csb.app/node_modules/rc-dropdown/es/Dropdown.js:29:28)
    at Dropdown (https://g7sg44.csb.app/node_modules/antd/es/dropdown/dropdown.js:34:16)
    at DensityIcon (https://g7sg44.csb.app/node_modules/@ant-design/pro-table/es/components/ToolBar/DensityIcon.js:16:44)
    at eval (https://g7sg44.csb.app/node_modules/@rc-component/trigger/es/TriggerWrapper.js:9:24)
    at DomWrapper (https://g7sg44.csb.app/node_modules/rc-resize-observer/es/SingleObserver/DomWrapper.js:27:33)
    at SingleObserver (https://g7sg44.csb.app/node_modules/rc-resize-observer/es/SingleObserver/index.js:17:24)
    at ResizeObserver (https://g7sg44.csb.app/node_modules/rc-resize-observer/es/index.js:26:24)
    at eval (https://g7sg44.csb.app/node_modules/@rc-component/trigger/es/index.js:51:34)
    at Tooltip (https://g7sg44.csb.app/node_modules/rc-tooltip/es/Tooltip.js:21:32)
    at eval (https://g7sg44.csb.app/node_modules/antd/es/tooltip/index.js:37:21)
    at span
    at div
    at div
    at div
    at div
    at div
    at DomWrapper (https://g7sg44.csb.app/node_modules/rc-resize-observer/es/SingleObserver/DomWrapper.js:27:33)
    at SingleObserver (https://g7sg44.csb.app/node_modules/rc-resize-observer/es/SingleObserver/index.js:17:24)
    at ResizeObserver (https://g7sg44.csb.app/node_modules/rc-resize-observer/es/index.js:26:24)
    at ListToolBar (https://g7sg44.csb.app/node_modules/@ant-design/pro-table/es/components/ListToolBar/index.js:86:34)
    at ToolBar (https://g7sg44.csb.app/node_modules/@ant-design/pro-table/es/components/ToolBar/index.js:99:27)
    at ToolbarRender (https://g7sg44.csb.app/node_modules/@ant-design/pro-table/es/components/ToolBar/index.js:179:33)
    at div
    at div
    at eval (https://g7sg44.csb.app/node_modules/@ant-design/pro-card/es/components/Card/index.js:38:25)
    at div
    at TableRender (https://g7sg44.csb.app/node_modules/@ant-design/pro-table/es/Table.js:53:22)
    at ProTable (https://g7sg44.csb.app/node_modules/@ant-design/pro-table/es/Table.js:246:28)
    at ErrorBoundary (https://g7sg44.csb.app/node_modules/@ant-design/pro-utils/es/components/ErrorBoundary/index.js:34:33)
    at MotionWrapper (https://g7sg44.csb.app/node_modules/antd/es/config-provider/MotionWrapper.js:11:20)
    at ProviderChildren (https://g7sg44.csb.app/node_modules/antd/es/config-provider/index.js:130:20)
    at ConfigProvider (https://g7sg44.csb.app/node_modules/antd/es/config-provider/index.js:302:25)
    at ConfigProviderContainer (https://g7sg44.csb.app/node_modules/@ant-design/pro-provider/es/index.js:74:24)
    at LocaleProvider (https://g7sg44.csb.app/node_modules/antd/es/locale/index.js:24:10)
    at MotionWrapper (https://g7sg44.csb.app/node_modules/antd/es/config-provider/MotionWrapper.js:11:20)
    at ProviderChildren (https://g7sg44.csb.app/node_modules/antd/es/config-provider/index.js:130:20)
    at ConfigProvider (https://g7sg44.csb.app/node_modules/antd/es/config-provider/index.js:302:25)
    at ProConfigProvider (https://g7sg44.csb.app/node_modules/@ant-design/pro-provider/es/index.js:160:24)
    at Container (https://g7sg44.csb.app/node_modules/@ant-design/pro-table/es/Store/Provide.js:168:34)
    at ProviderTableContainer (https://g7sg44.csb.app/node_modules/@ant-design/pro-table/es/Table.js:605:48)
    at eval (https://g7sg44.csb.app/App.tsx:146:39)
```

### 📷 复现步骤
打开控制台即可看见

### 🏞 期望结果
无警告提示

### 💻 复现代码
https://codesandbox.io/s/cha-xun-biao-ge-forked-g7sg44?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 2.6.35
- umi 版本 无
- 浏览器环境 chrome 119.0.6045.105
- 开发环境 [e.g. mac OS]  mac OS 14

**Comment by fnoopv** [comment]
#6156
