### ISSUE TITLE
🧐[问题] 升级依赖`@umijs/max`和`@ant-design/pro-components`到最新版，控制台报错

### ISSUE THREAD

**Issue by kjxbyz** [ant-design/pro-components#7889]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

升级依赖`@umijs/max`和`@ant-design/pro-components`到最新版，控制台报错

### 🚑 其他信息

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ProLayout`.
    at ProLayout (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:98371:28)
    at http://localhost:8004/admin/umi__plugin-layout__Layout.async.js:210:66
    at Suspense
    at RemoteComponent (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:159768:25)
    at Routes (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:159311:76)
    at Router (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:159039:15)
    at BrowserRoutes (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:159271:23)
    at r (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:442184:7320)
    at Provider (http://localhost:8004/admin/src_umi_umi_ts.async.js:16014:74)
    at Provider (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:155782:3)
    at RootContainer (http://localhost:8004/admin/src_umi_umi_ts.async.js:16214:68)
    at InitialStateProvider (http://localhost:8004/admin/src_umi_umi_ts.async.js:16823:111)
    at Provider (http://localhost:8004/admin/src_umi_umi_ts.async.js:17219:34)
    at ProviderWrapper (http://localhost:8004/admin/src_umi_umi_ts.async.js:17427:108)
    at Browser (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:159376:68)
console.<computed> @ mf-dep____vendor.ba1c6fe7.js:442014
printWarning @ mf-dep____vendor.ba1c6fe7.js:449905
error @ mf-dep____vendor.ba1c6fe7.js:449881
jsxWithValidation @ mf-dep____vendor.ba1c6fe7.js:450940
jsxWithValidationDynamic @ mf-dep____vendor.ba1c6fe7.js:450997
ProLayout @ mf-dep____vendor.ba1c6fe7.js:98381
renderWithHooks @ mf-dep____vendor.ba1c6fe7.js:429523
mountIndeterminateComponent @ mf-dep____vendor.ba1c6fe7.js:432349
beginWork @ mf-dep____vendor.ba1c6fe7.js:433587
beginWork$1 @ mf-dep____vendor.ba1c6fe7.js:438473
performUnitOfWork @ mf-dep____vendor.ba1c6fe7.js:437309
workLoopSync @ mf-dep____vendor.ba1c6fe7.js:437240
renderRootSync @ mf-dep____vendor.ba1c6fe7.js:437203
performSyncWorkOnRoot @ mf-dep____vendor.ba1c6fe7.js:436826
（匿名） @ mf-dep____vendor.ba1c6fe7.js:425865
unstable_runWithPriority @ mf-dep____vendor.ba1c6fe7.js:462549
runWithPriority$1 @ mf-dep____vendor.ba1c6fe7.js:425814
flushSyncCallbackQueueImpl @ mf-dep____vendor.ba1c6fe7.js:425860
workLoop @ mf-dep____vendor.ba1c6fe7.js:462498
flushWork @ mf-dep____vendor.ba1c6fe7.js:462471
performWorkUntilDeadline @ mf-dep____vendor.ba1c6fe7.js:462238
mf-dep____vendor.ba1c6fe7.js:439591 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ProLayout`.
    at createFiberFromTypeAndProps (mf-dep____vendor.ba1c6fe7.js:439591:21)
    at createFiberFromElement (mf-dep____vendor.ba1c6fe7.js:439619:15)
    at reconcileSingleElement (mf-dep____vendor.ba1c6fe7.js:428590:23)
    at reconcileChildFibers (mf-dep____vendor.ba1c6fe7.js:428650:35)
    at reconcileChildren (mf-dep____vendor.ba1c6fe7.js:431528:28)
    at updateContextProvider (mf-dep____vendor.ba1c6fe7.js:433237:3)
    at beginWork (mf-dep____vendor.ba1c6fe7.js:433649:14)
    at HTMLUnknownElement.callCallback (mf-dep____vendor.ba1c6fe7.js:418483:14)
    at Object.invokeGuardedCallbackDev (mf-dep____vendor.ba1c6fe7.js:418532:16)
    at invokeGuardedCallback (mf-dep____vendor.ba1c6fe7.js:418594:31)
    at beginWork$1 (mf-dep____vendor.ba1c6fe7.js:438497:7)
    at performUnitOfWork (mf-dep____vendor.ba1c6fe7.js:437309:12)
    at workLoopSync (mf-dep____vendor.ba1c6fe7.js:437240:5)
    at renderRootSync (mf-dep____vendor.ba1c6fe7.js:437203:7)
    at performSyncWorkOnRoot (mf-dep____vendor.ba1c6fe7.js:436826:18)
    at mf-dep____vendor.ba1c6fe7.js:425865:26
    at unstable_runWithPriority (mf-dep____vendor.ba1c6fe7.js:462549:12)
    at runWithPriority$1 (mf-dep____vendor.ba1c6fe7.js:425814:10)
    at flushSyncCallbackQueueImpl (mf-dep____vendor.ba1c6fe7.js:425860:9)
    at workLoop (mf-dep____vendor.ba1c6fe7.js:462498:34)
    at flushWork (mf-dep____vendor.ba1c6fe7.js:462471:14)
    at MessagePort.performWorkUntilDeadline (mf-dep____vendor.ba1c6fe7.js:462238:27)
createFiberFromTypeAndProps @ mf-dep____vendor.ba1c6fe7.js:439591
createFiberFromElement @ mf-dep____vendor.ba1c6fe7.js:439619
reconcileSingleElement @ mf-dep____vendor.ba1c6fe7.js:428590
reconcileChildFibers @ mf-dep____vendor.ba1c6fe7.js:428650
reconcileChildren @ mf-dep____vendor.ba1c6fe7.js:431528
updateContextProvider @ mf-dep____vendor.ba1c6fe7.js:433237
beginWork @ mf-dep____vendor.ba1c6fe7.js:433649
callCallback @ mf-dep____vendor.ba1c6fe7.js:418483
invokeGuardedCallbackDev @ mf-dep____vendor.ba1c6fe7.js:418532
invokeGuardedCallback @ mf-dep____vendor.ba1c6fe7.js:418594
beginWork$1 @ mf-dep____vendor.ba1c6fe7.js:438497
performUnitOfWork @ mf-dep____vendor.ba1c6fe7.js:437309
workLoopSync @ mf-dep____vendor.ba1c6fe7.js:437240
renderRootSync @ mf-dep____vendor.ba1c6fe7.js:437203
performSyncWorkOnRoot @ mf-dep____vendor.ba1c6fe7.js:436826
（匿名） @ mf-dep____vendor.ba1c6fe7.js:425865
unstable_runWithPriority @ mf-dep____vendor.ba1c6fe7.js:462549
runWithPriority$1 @ mf-dep____vendor.ba1c6fe7.js:425814
flushSyncCallbackQueueImpl @ mf-dep____vendor.ba1c6fe7.js:425860
workLoop @ mf-dep____vendor.ba1c6fe7.js:462498
flushWork @ mf-dep____vendor.ba1c6fe7.js:462471
performWorkUntilDeadline @ mf-dep____vendor.ba1c6fe7.js:462238
mf-dep____vendor.ba1c6fe7.js:442014 The above error occurred in the <Context.Provider> component:

    at ProviderChildren (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:215224:24)
    at LocaleReceiver (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:222085:90)
    at ConfigProvider (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:215339:13)
    at ProLayout (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:98371:28)
    at http://localhost:8004/admin/umi__plugin-layout__Layout.async.js:210:66
    at Suspense
    at RemoteComponent (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:159768:25)
    at Routes (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:159311:76)
    at Router (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:159039:15)
    at BrowserRoutes (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:159271:23)
    at r (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:442184:7320)
    at Provider (http://localhost:8004/admin/src_umi_umi_ts.async.js:16014:74)
    at Provider (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:155782:3)
    at RootContainer (http://localhost:8004/admin/src_umi_umi_ts.async.js:16214:68)
    at InitialStateProvider (http://localhost:8004/admin/src_umi_umi_ts.async.js:16823:111)
    at Provider (http://localhost:8004/admin/src_umi_umi_ts.async.js:17219:34)
    at ProviderWrapper (http://localhost:8004/admin/src_umi_umi_ts.async.js:17427:108)
    at Browser (http://localhost:8004/admin/mf-dep____vendor.ba1c6fe7.js:159376:68)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.<computed> @ mf-dep____vendor.ba1c6fe7.js:442014
logCapturedError @ mf-dep____vendor.ba1c6fe7.js:434623
update.callback @ mf-dep____vendor.ba1c6fe7.js:434651
callCallback @ mf-dep____vendor.ba1c6fe7.js:426856
commitUpdateQueue @ mf-dep____vendor.ba1c6fe7.js:426877
commitLifeCycles @ mf-dep____vendor.ba1c6fe7.js:435269
commitLayoutEffects @ mf-dep____vendor.ba1c6fe7.js:437959
callCallback @ mf-dep____vendor.ba1c6fe7.js:418483
invokeGuardedCallbackDev @ mf-dep____vendor.ba1c6fe7.js:418532
invokeGuardedCallback @ mf-dep____vendor.ba1c6fe7.js:418594
commitRootImpl @ mf-dep____vendor.ba1c6fe7.js:437684
unstable_runWithPriority @ mf-dep____vendor.ba1c6fe7.js:462549
runWithPriority$1 @ mf-dep____vendor.ba1c6fe7.js:425814
commitRoot @ mf-dep____vendor.ba1c6fe7.js:437523
performSyncWorkOnRoot @ mf-dep____vendor.ba1c6fe7.js:436862
（匿名） @ mf-dep____vendor.ba1c6fe7.js:425865
unstable_runWithPriority @ mf-dep____vendor.ba1c6fe7.js:462549
runWithPriority$1 @ mf-dep____vendor.ba1c6fe7.js:425814
flushSyncCallbackQueueImpl @ mf-dep____vendor.ba1c6fe7.js:425860
workLoop @ mf-dep____vendor.ba1c6fe7.js:462498
flushWork @ mf-dep____vendor.ba1c6fe7.js:462471
performWorkUntilDeadline @ mf-dep____vendor.ba1c6fe7.js:462238
mf-dep____vendor.ba1c6fe7.js:439591 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ProLayout`.
    at createFiberFromTypeAndProps (mf-dep____vendor.ba1c6fe7.js:439591:21)
    at createFiberFromElement (mf-dep____vendor.ba1c6fe7.js:439619:15)
    at reconcileSingleElement (mf-dep____vendor.ba1c6fe7.js:428590:23)
    at reconcileChildFibers (mf-dep____vendor.ba1c6fe7.js:428650:35)
    at reconcileChildren (mf-dep____vendor.ba1c6fe7.js:431528:28)
    at updateContextProvider (mf-dep____vendor.ba1c6fe7.js:433237:3)
    at beginWork (mf-dep____vendor.ba1c6fe7.js:433649:14)
    at HTMLUnknownElement.callCallback (mf-dep____vendor.ba1c6fe7.js:418483:14)
    at Object.invokeGuardedCallbackDev (mf-dep____vendor.ba1c6fe7.js:418532:16)
    at invokeGuardedCallback (mf-dep____vendor.ba1c6fe7.js:418594:31)
    at beginWork$1 (mf-dep____vendor.ba1c6fe7.js:438497:7)
    at performUnitOfWork (mf-dep____vendor.ba1c6fe7.js:437309:12)
    at workLoopSync (mf-dep____vendor.ba1c6fe7.js:437240:5)
    at renderRootSync (mf-dep____vendor.ba1c6fe7.js:437203:7)
    at performSyncWorkOnRoot (mf-dep____vendor.ba1c6fe7.js:436826:18)
    at mf-dep____vendor.ba1c6fe7.js:425865:26
    at unstable_runWithPriority (mf-dep____vendor.ba1c6fe7.js:462549:12)
    at runWithPriority$1 (mf-dep____vendor.ba1c6fe7.js:425814:10)
    at flushSyncCallbackQueueImpl (mf-dep____vendor.ba1c6fe7.js:425860:9)
    at workLoop (mf-dep____vendor.ba1c6fe7.js:462498:34)
    at flushWork (mf-dep____vendor.ba1c6fe7.js:462471:14)
    at MessagePort.performWorkUntilDeadline (mf-dep____vendor.ba1c6fe7.js:462238:27)
```

**Comment by annilq** [comment]
同错，有解决方案了吗？

**Comment by chenshuai2144** [comment]
问题：升级依赖`@umijs/max`和`@ant-design/pro-components`到最新版，控制台报错的问题。

解答：根据你提供的片段，你想要升级的是`@umijs/max`和`@ant-design/pro-components`依赖。根据你的描述，你已经在项目的`package.json`文件中进行了相应的更新操作。然后，你删除了`node_modules`目录，并执行了`npm install`命令来重新安装依赖。

接下来，你提到控制台报错。在升级依赖后，你可能会遇到一些兼容性问题或者其他错误。为了解决这个问题，你可以尝试以下几个步骤：

1. 确保你已经按照正确的方式升级了依赖，包括正确的版本号。
2. 运行`npm install`命令之前，确保你已经完全删除了旧的依赖，包括`node_modules`目录和`package-lock.json`文件。可以使用`npm cache clean --force`命令来清除缓存。
3. 检查控制台报错信息，看看是什么错误和提示。根据错误信息，你可能需要查看官方文档或者其他资源来找到解决方案。
4. 确认你的代码是否有其他地方依赖了旧版本的依赖，可能需要进行相应的更新和改动。
5. 如果以上步骤都没有解决问题，你可以尝试向umi 相关社区或者技术支持寻求帮助，他们可能能够提供更具体的解决方案。

希望以上回答能够帮助到你解决问题！如果还有其他问题，请随时提问。

**Comment by robin536180** [comment]
> 同错，有解决方案了吗？

请问解决了吗
