### ISSUE TITLE
🧐[问题]Ubuntu系统下运行npm start报错

### ISSUE THREAD

**Issue by 18601312306** [ant-design/pro-components#805]
### 🧐 问题描述
Ubuntu下运行npm start启动时报错，如下所示：
（是否支持Ubuntu系统？）
Unexpected token {
/home/develop/project/HuilinFund/client/huilin-client/node_modules/copy-webpack-plugin/node_modules/p-limit/index.js:30
  } catch {}
          ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Module._compile (/home/develop/project/HuilinFund/client/huilin-client/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.newLoader [as .js] (/home/develop/project/HuilinFund/client/huilin-client/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
develop@wanglongxiang:~/project/HuilinFund/client/huilin-client$

**Comment by chenshuai2144** [comment]
升级 node 版本
