### ISSUE TITLE
🐛[BUG] pro-layout 报警告 findDOMNode is deprecated and will be removed in the next major release.

### ISSUE THREAD

**Issue by rongxingsun** [ant-design/pro-components#8686]
ActionsContent.js

children: /*#__PURE__*/_jsx(ResizeObserver, {
        onResize: function onResize(_ref3) {
          var width = _ref3.width;
          setRightSizeDebounceFn.run(width);
        },
        children: contentRender ? /*#__PURE__*/_jsx("div", {
          style: {
            display: 'flex',
            alignItems: 'center',
            height: '100%',
            justifyContent: 'flex-end'
          },
          children: contentRender(_objectSpread(_objectSpread({}, props), {}, {
            // 测试专用
            //@ts-ignore
            rightContentSize: rightSize
          }))
        }) 

pageHeader/index.js

return wrapSSR( /*#__PURE__*/_jsx(ResizeObserver, {
    onResize: onResize,
    children: /*#__PURE__*/_jsxs("div", {
      className: className,
      style: style,
      children: [breadcrumbDom, title, childDom, footerDom]
    })
  }));

**Comment by resetsix** [comment]
see https://github.com/ant-design/pro-components/discussions/8837

**Comment by KoWhite** [comment]
+1

**Comment by KoWhite** [comment]
"dependencies": {
    "@ant-design/icons": "^4.8.1",
    "@ant-design/pro-components": "^2.8.6",
    "@dnd-kit/core": "^6.1.0",
    "@dnd-kit/modifiers": "^7.0.0",
    "@dnd-kit/sortable": "^8.0.0",
    "@dnd-kit/utilities": "^3.2.2",
    "@pkg/common": "workspace:*",
    "@umijs/route-utils": "^2.2.2",
    "@unocss/cli": "^0.64.0",
    "ahooks": "^3.8.1",
    "antd": "^5.24.1",
    "antd-style": "^3.6.1",
    "classnames": "^2.5.1",
    "dayjs": "^1.11.13",
    "lodash": "^4.17.21",
    "moment": "^2.30.1",
    "omit.js": "^2.0.2",
    "querystring": "^0.2.1",
    "rc-menu": "^9.12.4",
    "rc-util": "^5.38.1",
    "rc-virtual-list": "^3.17.1",
    "react": "^18.2.0",
    "react-dnd": "^16.0.1",
    "react-dnd-html5-backend": "^16.0.1",
    "react-dom": "^18.2.0",
    "react-helmet-async": "^1.3.0",
    "unocss": "^0.64.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^3.3.0",
    "@iconify-json/mdi": "^1.2.1",
    "@pkg/config-umi": "workspace:*",
    "@svgr/core": "^8.1.0",
    "@svgr/plugin-jsx": "^8.1.0",
    "@testing-library/react": "^13.4.0",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.21",
    "@types/history": "^4.7.11",
    "@types/lodash": "^4.14.202",
    "@types/react": "^18.2.48",
    "@types/react-dom": "^18.2.18",
    "@types/react-helmet": "^6.1.11",
    "@umijs/fabric": "^2.14.1",
    "@umijs/lint": "^4.1.1",
    "@umijs/max": "^4.1.1",
    "cross-env": "^7.0.3",
    "eslint": "^8.56.0",
    "express": "^4.18.2",
    "gh-pages": "^3.2.3",
    "lint-staged": "^10.5.4",
    "mockjs": "^1.1.0",
    "prettier": "^2.8.8",
    "prettier-plugin-organize-imports": "^3.2.2",
    "prettier-plugin-packagejson": "^2.4.3",
    "react-dev-inspector": "^1.9.0",
    "swagger-ui-dist": "^4.19.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.3.3",
    "umi-presets-pro": "^2.0.3",
    "umi-serve": "^1.9.11",
    "unplugin-auto-import": "^0.18.3",
    "unplugin-icons": "^0.20.1"
  },

这是我引入的依赖，同样也出现了此报错

报错内容：
Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node Error Component Stack
    at SingleObserver (index.js:20:24)
    at ResizeObserver (index.js:23:24)
    at eval (index.js:60:34)
    at Tooltip (Tooltip.js:25:32)
    at eval (index.js:49:18)
    at MenuItemTooltip (BaseMenu.js:48:73)
    at span (<anonymous>)
    at li (<anonymous>)
    at DomWrapper (DomWrapper.js:23:90)
    at SingleObserver (index.js:20:24)
    at ResizeObserver (index.js:23:24)
    at InternalItem (Item.js:20:25)
    at InternalRawItem (RawItem.js:20:52)
    at LegacyMenuItem (MenuItem.js:62:90)
    at eval (MenuItem.js:93:21)
    at MenuItem (MenuItem.js:217:24)
    at MenuItem (MenuItem.js:27:5)
    at InheritableContextProvider (MenuContext.js:30:23)
    at ul (<anonymous>)
    at DomWrapper (DomWrapper.js:23:90)
    at SingleObserver (index.js:20:24)
    at ResizeObserver (index.js:23:24)
    at Overflow (Overflow.js:40:32)
    at InheritableContextProvider (MenuContext.js:30:23)
    at eval (Menu.js:75:27)
    at eval (menu.js:59:55)
    at eval (index.js:21:64)
    at BaseMenu (BaseMenu.js:342:20)
    at MotionWrapper (MotionWrapper.js:16:5)
    at ProviderChildren (index.js:139:5)
    at ConfigProvider (index.js:440:54)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at TopNavHeader (index.js:36:58)
    at header (<anonymous>)
    at eval (layout.js:56:18)
    at Header (<anonymous>)
    at MotionWrapper (MotionWrapper.js:16:5)
    at ProviderChildren (index.js:139:5)
    at ConfigProvider (index.js:440:54)
    at DefaultHeader (index.js:39:24)
    at div (<anonymous>)
    at div (<anonymous>)
    at eval (layout.js:76:42)
    at Layout (<anonymous>)
    at div (<anonymous>)
    at BaseProLayout (ProLayout.js:213:13)
    at MotionWrapper (MotionWrapper.js:16:5)
    at ProviderChildren (index.js:139:5)
    at ConfigProvider (index.js:440:54)
    at ConfigProviderContainer (index.js:187:24)
    at LocaleProvider (index.js:22:5)
    at MotionWrapper (MotionWrapper.js:16:5)
    at ProviderChildren (index.js:139:5)
    at ConfigProvider (index.js:440:54)
    at ProConfigProvider (index.js:314:24)
    at MotionWrapper (MotionWrapper.js:16:5)
    at ProviderChildren (index.js:139:5)
    at ConfigProvider (index.js:440:54)
    at ProLayout (ProLayout.js:549:28)
    at eval (Layout.tsx:101:73)
    at Suspense (<anonymous>)
    at RemoteComponent (routes.js:122:25)
    at Routes (browser.js:82:76)
    at Router (index.js:854:15)
    at BrowserRoutes (browser.js:42:23)
    at r (index.module.js:17:7350)
    at Provider (runtime.tsx:26:74)
    at InitialStateProvider (Provider.tsx:30:64)
    at Provider (index.tsx:95:34)
    at ProviderWrapper (runtime.tsx:29:61)
    at MotionWrapper (MotionWrapper.js:16:5)
    at ProviderChildren (index.js:139:5)
    at ConfigProvider (index.js:440:54)
    at AntdProvider (runtime.tsx:57:23)

**Comment by leshalv** [comment]
升级最新版本
