### ISSUE TITLE
🐛[BUG] 引入ProForm就出现错误

### ISSUE THREAD

**Issue by xlorne** [ant-design/pro-components#8717]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

引入ProForm就出现错误

```
Uncaught TypeError: Cannot set properties of null (setting 'nativeElement')
    at ref (BaseForm.js:538:1)
    at refObject (react-dom.development.js:16316:1)
    at safelyCallDestroy (react-dom.development.js:22971:1)
    at commitHookEffectListUnmount (react-dom.development.js:23139:1)
    at invokeLayoutEffectUnmountInDEV (react-dom.development.js:25214:1)
    at invokeEffectsInDev (react-dom.development.js:27390:1)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27360:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27095:1)
    at flushPassiveEffects (react-dom.development.js:27023:1)
```

### 📷 复现步骤

运行起来就出现错误，yarn start

### 🏞 期望结果

正常展示 ProForm

### 💻 复现代码
[my-app.tar.gz](https://github.com/user-attachments/files/16957293/my-app.tar.gz)

### © 版本信息

- ProComponents 版本: 2.7.15
- umi 版本 无
- 浏览器环境 chrome latest
- 开发环境 macos

### 🚑 其他信息

这个项目是通过npx create-react-app my-app --template=typescript 创建的，
创建以后就添加了antd和@ant-design/pro-components 依赖，并没有做任何其他的操作。

**Comment by xlorne** [comment]
@ant-design/pro-components": "2.7.16 版本有bug，
由于我的package.json下配置的版本是最新版
"@ant-design/pro-components": "^2.7.15"
自动升级到2.7.16上了，就会出现错误，但是如果固定2.7.15的话就不会有问题
