### ISSUE TITLE
🐛[BUG] 引入ProForm就出现错误 2.7.16 存在BUG无法正常使用ProForm

### ISSUE THREAD

**Issue by xlorne** [ant-design/pro-components#8718]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

引入ProForm就出现错误

```
Uncaught TypeError: Cannot set properties of null (setting 'nativeElement')
    at ref (BaseForm.js:538:1)
    at refObject (react-dom.development.js:16316:1)
    at safelyCallDestroy (react-dom.development.js:22971:1)
    at commitHookEffectListUnmount (react-dom.development.js:23139:1)
    at invokeLayoutEffectUnmountInDEV (react-dom.development.js:25214:1)
    at invokeEffectsInDev (react-dom.development.js:27390:1)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27360:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27095:1)
    at flushPassiveEffects (react-dom.development.js:27023:1)
```

### 📷 复现步骤

运行起来就出现错误，yarn start

### 🏞 期望结果

正常展示 ProForm

### 💻 复现代码
[my-app.tar.gz](https://github.com/user-attachments/files/16957293/my-app.tar.gz)

### © 版本信息

- ProComponents 版本: 2.7.16
- umi 版本 无
- 浏览器环境 chrome latest
- 开发环境 macos

### 🚑 其他信息

这个项目是通过npx create-react-app my-app --template=typescript 创建的，
创建以后就添加了antd和@ant-design/pro-components 依赖，并没有做任何其他的操作。

**Comment by xlorne** [comment]
在package.json 上锁定2.7.15可以解决问题 
```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@ant-design/pro-components": "2.7.15",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.7.13",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "antd": "^5.20.3",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-scripts": "5.0.1",
    "typescript": "^4.4.2",
    "web-vitals": "^2.1.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by xlorne** [comment]
另外在"@ant-design/pro-form" "2.29.0" 下存在代码编译错误问题问题

@ant-design/pro-form/es/components/FormItemRender/index.d.ts 

```
import { Form } from 'antd';
import React from 'react';
interface ControlPropsType {
    id: string;
    value: any;
    onChange: (value: any, ...args: any[]) => void;
}
export type WithControlPropsType<T = object> = T & Partial<ControlPropsType>;
interface ControlModelType {
    value: any;
    onChange: (value: any) => void;
}
interface FormControlProps {
    valuePropName?: string;
    trigger?: string;
}
interface FormControlMultiProps extends FormControlProps {
    name: string;
}
type GetArrayFieldType<T extends readonly {
    name: string;
}[]> = T[number]['name'];
export declare function useControlModel<T extends FormControlProps>({ value, onChange, id }: WithControlPropsType, model?: T): ControlModelType;
// 下面的const T extends readonly string[]应该改为 T extends readonly string[]
export declare function useControlModel<const T extends readonly string[]>({ value, onChange, id }: WithControlPropsType, model?: T): {
    [P in T[number]]: ControlModelType;
};
// 下面的const T extends readonly FormControlMultiProps[]应该改为 T extends readonly FormControlMultiProps[]
export declare function useControlModel<const T extends readonly FormControlMultiProps[]>({ value, onChange, id }: WithControlPropsType, model?: T): {
    [P in GetArrayFieldType<T>]: ControlModelType;
};
export type FormControlFC<P> = (props: WithControlPropsType<P>) => React.ReactNode;
type FormControlInjectProps = ReturnType<typeof Form.Item.useStatus> & {
    id: string;
    value: any;
    onChange: (value: any) => void;
    [x: string]: any;
};
/**
 * 用在 ProForm.Item 或 Form.Item 于 表单项之间的，用于劫持渲染的函数
 * ``` tsx
 * <Form.Item name='name' label='名称'>
 *   <FormControlRender>
 *   {
 *     formItemProps => (
 *       <div>
 *         <span>prefix</span>
 *         <Input {...formItemProps} />
 *       </div>
 *     )
 *   }
 *   </FormControlRender>
 * </Form.Item>
 * ```
 */
export declare function FormControlRender(props: WithControlPropsType<{
    children: (props: FormControlInjectProps) => React.ReactElement;
}>): React.ReactElement<any, string | React.JSXElementConstructor<any>>;
/**
 * 提取props中的 value 和 onChange 属性
 */
export declare function pickControlProps(props: FormControlInjectProps): {
    value: any;
    onChange: (value: any) => void;
};
/**
 * 提取props中的 value、onChange 和 id 属性
 */
export declare function pickControlPropsWithId(props: FormControlInjectProps): {
    id: string;
    value: any;
    onChange: (value: any) => void;
};
/**
 * 用于包裹ProForm.Item Form.Item，使其可以使用render props的形式
 * @description 用法
 * const FormItem = withFormItemRender(用于包裹ProForm.Item)
 * ``` tsx
 * <FormItem name='name' label='名称'>
 *   {
 *     formItemProps => (
 *       <div>
 *         <span>prefix</span>
 *         <Input {...formItemProps} />
 *       </div>
 *     )
 *   }
 * </FormItem>
 * ```
 */
export declare function withFormItemRender<T extends React.FC<any>>(Comp: T): React.FC<Omit<React.ComponentProps<T>, 'children'> & {
    children: (formItemProps: FormControlInjectProps) => React.ReactNode;
}>;
/**
 * 用 withFormItemRender 加工Form.Item，使其拥有render props能力，同时暴露出 status 属性方便自定义组件校验使用
 *
 * ``` tsx
 *   <FormItemRender name='name' label='名称'>
 *   {
 *     formItemProps => (
 *       <div>
 *         <h3>prefix</h3>
 *         <textarea {...formItemProps} style={{ borderColor: formItemProps.status === 'error' ? 'red' : undefined }} />
 *       </div>
 *     )
 *   }
 *   </FormItemRender>
 * ```
 */
export declare const FormItemRender: React.FC<Omit<import("antd").FormItemProps<unknown>, "children"> & {
    children: (formItemProps: FormControlInjectProps) => React.ReactNode;
}>;
/**
 * 用 withFormItemRender 加工 ProForm.Item，使其拥有render props能力，同时暴露出 status 属性方便自定义组件校验使用
 * ``` tsx
 *   <ProFormItemRender name='name' label='名称'>
 *   {
 *     formItemProps => (
 *       <div>
 *         <h3>prefix</h3>
 *         <textarea {...formItemProps} style={{ borderColor: formItemProps.status === 'error' ? 'red' : undefined }} />
 *       </div>
 *     )
 *   }
 *   </ProFormItemRender>
 * ```
 */
export declare const ProFormItemRender: React.FC<Omit<import("antd").FormItemProps<any> & {
    ignoreFormItem?: boolean | undefined;
    valueType?: import("../../../../utils/src").ProFieldValueType | undefined;
    transform?: import("../../../../utils/src").SearchTransformKeyFn | undefined;
    dataFormat?: string | undefined;
    lightProps?: import("../..").LightWrapperProps | undefined;
    proFormFieldKey?: any;
} & {
    addonBefore?: React.ReactNode;
    addonAfter?: React.ReactNode;
    addonWarpStyle?: React.CSSProperties | undefined;
    convertValue?: import("../../../../utils/src").SearchConvertKeyFn | undefined;
    help?: React.ReactNode | ((params: {
        errors: React.ReactNode[];
        warnings: React.ReactNode[];
    }) => React.ReactNode);
}, "children"> & {
    children: (formItemProps: FormControlInjectProps) => React.ReactNode;
}>;
export {};

```

**Comment by CSpy163** [comment]
Nextjs 14.2.10 + procomponents 2.7.15还会是报这个错误

**Comment by Developer024** [comment]
> 在package.json 上锁定2.7.15可以解决问题
> 
> ```
> {
>   "name": "my-app",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "@ant-design/pro-components": "2.7.15",
>     "@testing-library/jest-dom": "^5.14.1",
>     "@testing-library/react": "^13.0.0",
>     "@testing-library/user-event": "^13.2.1",
>     "@types/jest": "^27.0.1",
>     "@types/node": "^16.7.13",
>     "@types/react": "^18.0.0",
>     "@types/react-dom": "^18.0.0",
>     "antd": "^5.20.3",
>     "react": "^18.3.1",
>     "react-dom": "^18.3.1",
>     "react-scripts": "5.0.1",
>     "typescript": "^4.4.2",
>     "web-vitals": "^2.1.0"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject"
>   },
>   "eslintConfig": {
>     "extends": [
>       "react-app",
>       "react-app/jest"
>     ]
>   },
>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   }
> }
> ```

yes，2.7.15不存在这个问题。目前可以锁住这个版本

**Comment by xlorne** [comment]
测试，后面更新2.7.19版本就没有错了，同时由于pro-compoents采用了typescript 5.x的语法，所以需要将 typescript升级到5.x以上的版本。
