### ISSUE TITLE
findDOMNode is deprecated and will be removed in the next major release.

### ISSUE THREAD

**Issue by yuzh0816** [ant-design/pro-components#8752]
### Reproduction link

[https://github.com/yuzh0816/antd-test](https://github.com/yuzh0816/antd-test)

### Steps to reproduce

执行npm run dev后，打开控制台即可看到报错

### What is expected?

希望这处报错被解决。

### What is actually happening?

报错：
Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. 

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | 18.3.1 |
| System | Windows Server 2022 |
| Browser | 所有浏览器 |

**Comment by afc163** [comment]
看上去是 ProLayout 的实现问题。

**Comment by afc163** [comment]
有不少类似问题：https://github.com/ant-design/pro-components/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+findDOMNode

**Comment by researchlab** [comment]
使用 ProTable 也报这个错误 

**版本信息**
"dependencies": {
    "@ant-design/icons": "^5.4.0",
    "@ant-design/pro-components": "^2.7.15",
    "@apollo/client": "^3.11.4",
    "@types/lodash": "^4.17.7",
    "antd": "5.20.3",
    "antd-img-crop": "^4.23.0",
    "graphql": "^16.9.0",
    "lodash": "^4.17.21",
    "pro-components": "link: @ant-design/pro-components",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "6.6.1",
    "vite-plugin-eslint": "^1.8.1"
  },

**使用方式**
```tsx
import { ActionType, PageContainer, ProTable } from '@ant-design/pro-components';

<ProTable /> 
```

注释掉<ProTable /> 就不报错

**浏览器报错信息**
**Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node Error Component Stack** 
    at SingleObserver (index.js:10:24)
    at ResizeObserver2 (index.js:12:24)
    at index.js:33:34
    at Tooltip2 (Tooltip.js:11:32)
    at index.js:30:16
    at span (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at DomWrapper3 (DomWrapper.js:13:5)
    at SingleObserver (index.js:10:24)
    at ResizeObserver2 (index.js:12:24)
    at ListToolBar2 (index.js:93:34)
    at ToolBar (index.js:91:27)
    at ToolbarRender2 (index.js:186:5)
    at div (<anonymous>)
    at div (<anonymous>)
    at index.js:23:25
    at div (<anonymous>)
    at TableRender (Table.js:37:22)
    at ProTable2 (Table.js:295:28)
    at ErrorBoundary2 (index.js:17:5)
    at ProConfigProvider2 (index.js:242:24)
    at Container2 (Provide.js:199:34)
    at ProviderTableContainer2 (Table.js:806:21)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at GridContent2 (index.js:15:15)
    at div (<anonymous>)
    at PageContainerBase2 (index.js:172:24)
    at ProConfigProvider2 (index.js:242:24)
    at PageContainer2 (<anonymous>)
    at Product (index.tsx:16:18)
    at RenderedRoute (hooks.tsx:566:26)
    at div (<anonymous>)
    at main (<anonymous>)
    at layout.js:39:18
    at Content (<anonymous>)
    at ErrorBoundary2 (index.js:17:5)
    at WrapContent2 (WrapContent.js:9:21)
    at div (<anonymous>)
    at div (<anonymous>)
    at layout.js:59:13
    at Layout (<anonymous>)
    at div (<anonymous>)
    at BaseProLayout2 (ProLayout.js:171:13)
    at MotionWrapper (MotionWrapper.js:8:5)
    at ProviderChildren (index.js:105:5)
    at ConfigProvider (index.js:394:25)
    at SWRConfig (index.mjs:529:13)
    at ConfigProviderContainer2 (index.js:115:24)
    at LocaleProvider (index.js:11:5)
    at MotionWrapper (MotionWrapper.js:8:5)
    at ProviderChildren (index.js:105:5)
    at ConfigProvider (index.js:394:25)
    at ProConfigProvider2 (index.js:242:24)
    at MotionWrapper (MotionWrapper.js:8:5)
    at ProviderChildren (index.js:105:5)
    at ConfigProvider (index.js:394:25)
    at ProLayout2 (ProLayout.js:507:28)
    at Layout (index.tsx:37:20)
    at RenderedRoute (hooks.tsx:566:26)
    at Routes (components.tsx:373:3)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at Spin (index.js:29:18)
    at UserInfo (index.tsx:10:21)
    at contextFactory.tsx:19:15
    at Router (components.tsx:291:13)
    at BrowserRouter (index.tsx:285:3)
    at ApolloProvider (ApolloProvider.tsx:15:9)


**解决方案之一**
看了上述讨论， 将react版本降到18.2.0 就不报错了

"react": "18.2.0",
"react-dom": "18.2.0",

**Comment by resetsix** [comment]
see https://github.com/ant-design/pro-components/discussions/8837

**Comment by leshalv** [comment]
升级到react 19，ant升级到最新版本，即可解决。
